#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"
require "#{APP_PATH}/config/environment"

#Mailman.config.logger = Logger.new("log/mailman.log")  # uncomment this if you can want to #create a log file
Mailman.config.poll_interval = 3  # change this number as per your needs. Default is 60 seconds
Mailman.config.imap = {
  server: 'smtp.gmail.com', port: 995, ssl: true,
  username: ENV[GMAIL_USER],
  password: ENV[GMAIL_PASSWORD]
}
puts "------------------------------------------"
puts ENV[GMAIL_USER]
puts "------------------------------------------"
# address: "smtp.gmail.com",
#     port: 587,
#     domain: "gmail.com",
#     authentication: "plain",
#     enable_starttls_auto: true,
#     user_name: ENV["GMAIL_USERNAME"],
#     password: ENV["GMAIL_PASSWORD"]
Mailman::Application.run do
  default do
    begin
      p "Found a new message"
      p message.from.first # message.from is an array
      p message.to.first # message.to is an array again..
      p message.subject
      rescue Exception => e
        Mailman.logger.error "Exception occurred while receiving message:n#{message}"
        Mailman.logger.error [e, *e.backtrace].join("n")
      end
    end
  end
end